schoollibrary/bpslibrary/views/books.py
"""Handle book repository functionalities."""

# pylint: disable=C0103

from urllib import request as urllib_request
from time import sleep
import re
import random
import sqlite3
from flask import Blueprint, flash, redirect, render_template, request
from flask_paginate import Pagination, get_page_parameter
from sqlalchemy import exc, or_
from bpslibrary import app
from bpslibrary.database import db_session
from bpslibrary.models import Author, Book, Category
from bpslibrary.utils.barcode import scan_for_isbn
from bpslibrary.utils.apihandler import APIClient
from bpslibrary.utils.permission import admin_access_required
from bpslibrary.utils.enums import BookLocation
from bpslibrary.views.loans import init_loan_forms

mod = Blueprint('books', __name__, url_prefix='/books')
THUMBNAILS_ABSOLUTE_DIR = app.config['THUMBNAILS_ABSOLUTE_DIR']
THUMBNAILS_DIR = app.config['THUMBNAILS_DIR']
PER_PAGE = app.config['PER_PAGE']


@mod.route('/')
def index():
    """Render the default landing page for books."""
    return view_books()


@mod.route('/lookup', methods=['GET', 'POST'])
@admin_access_required
def lookup_book():
    """Look up book details online."""
    if request.method == 'GET':
        return render_template('add_book.html')

    if request.method == 'POST':
        found_books = []
        isbns = set()
        barcode_isbn = []
        input_isbn = request.form['isbn'].strip().split(',')
        book_title = request.form['book_title'].strip()
        barcode_file = None
        try:
            if 'barcode' in request.files:
                barcode_file = request.files['barcode']
                if not barcode_file.filename == '':
                    barcode_isbn = scan_for_isbn(barcode_file)

            if barcode_isbn or input_isbn or book_title:
                isbns = set(input_isbn + barcode_isbn)
                isbns.discard('')
                api_client = APIClient(isbns, book_title)
                found_books = api_client.find_books()

        except ValueError as e:
            flash("Something has gone wrong! <br>" + str(e), 'error')

        return render_template('add_book.html',
                               found_books=found_books,
                               search_title=book_title,
                               search_isbn=','.join(isbns)
                               if bool(isbns) else '')


@mod.route('/add', methods=['POST'])
@admin_access_required
def add_book():
    """Add a book to the library."""
    try:
        book = Book()
        # defaults
        book.is_available = True
        book.current_location = BookLocation.LIBRARY.value

        book.title = request.form['book_title'].strip()
        book.isbn10 = request.form['isbn10'].strip()
        book.isbn13 = request.form['isbn13'].strip()
        book.description = request.form['book_description'].strip()
        book.preview_url = request.form['preview_url'].strip()

        for author_name in request.form['book_authors'].split(','):
            author_name = author_name.strip()
            author = Author.query.filter(Author.name == author_name).first()
            if not author:
                author = Author(author_name)
            book.authors.append(author)

        for category_name in request.form['book_categories'].split(','):
            category_name = category_name.strip()
            category = Category.query.\
                filter(Category.name == category_name).first()
            if not category:
                category = Category(category_name)
            book.categories.append(category)

        book.thumbnail_url = request.form['thumbnail_url'].strip()
        if book.thumbnail_url:
            title = [c for c in book.title.replace(' ', '_')
                     if re.match(r'\w', c)]
            image_name = ''.join(title) + book.isbn13 + '.jpg'

            img = open(THUMBNAILS_ABSOLUTE_DIR + image_name, 'wb')
            img.write(urllib_request.urlopen(book.thumbnail_url).read())
            book.image_name = image_name

        session = db_session()
        session.add(book)
        session.commit()

        flash("The book has been added to the library successfully!")
    except RuntimeError as rte:
        error_message = "Something has gone wrong!"
        if isinstance(rte, exc.IntegrityError):
            error_message += "<br>It seems that the book '%s' "\
                "already exists in the library." % book.title

        flash(error_message, 'error')

    return render_template('add_book.html')


def validate_add_book():
    """Validate books on addition or modification."""
    return None


@mod.route('/edit', methods=['GET', 'POST'])
@admin_access_required
def edit_book():
    """Update a book in the library."""
    session = db_session()

    lookup_isbns = []
    lookup_titles = []
    books = session.query(Book).distinct().\
        values(Book.isbn10,
               Book.isbn13,
               Book.title)

    for book in books:
        if book[0]:
            lookup_isbns.append(book[0])
        if book[1]:
            lookup_isbns.append(book[1])
        if book[2]:
            lookup_titles.append(book[2])

    if lookup_isbns:
        lookup_isbns.sort()
    if lookup_titles:
        lookup_titles.sort()

    if request.method == 'GET':
        return render_template('edit_book.html',
                               lookup_isbns=lookup_isbns,
                               lookup_titles=lookup_titles)

    found_books = []

    if request.method == 'POST':
        search_isbn = request.form['search_isbn']
        search_title = request.form['search_title']

        if search_title and search_title.strip():
            search_term = '%' + search_title.strip() + '%'
            found_books = session.query(Book).\
                filter(Book.title.ilike(search_term)).all()

        if search_isbn and search_isbn.strip():
            search_term = '%' + search_isbn.strip() + '%'
            found_books = found_books + session.query(Book).\
                filter(or_(Book.isbn10.ilike(search_term),
                           Book.isbn13.ilike(search_term))).all()

    result = render_template('edit_book.html',
                             lookup_isbns=lookup_isbns,
                             lookup_titles=lookup_titles,
                             search_isbn=search_isbn,
                             search_title=search_title,
                             thumbnails_dir=THUMBNAILS_DIR,
                             found_books=sorted(found_books,
                                                key=lambda b: b.title))
    return result


@mod.route('/update', methods=['POST'])
@admin_access_required
def update_book():
    """Update a book with provided details."""
    try:
        session = db_session()

        update_id = request.form['book_id']
        update_status = int(request.form['book_status'].strip())
        update_title = request.form['book_title'].strip()
        update_description = request.form['book_description'].strip()
        update_thumbnail_url = request.form['book_thumbnail_url'].strip()
        update_preview_url = request.form['book_preview_url'].strip()
        update_categories = [c.strip() for c
                             in request.form['book_categories'].split(',')]
        update_authors = [a.strip() for a
                          in request.form['book_authors'].split(',')]

        book = session.query(Book).filter(Book.id == update_id).first()

        book.title = update_title
        book.description = update_description
        book.is_available = update_status

        # update categories
        # removed
        for category in book.categories:
            if category.name not in update_categories:
                book.categories.remove(category)
        # added
        for category_name in update_categories:
            if category_name not in [c.name for c in book.categories]:
                book.categories.append(Category(category_name))

        # update authors
        # removed
        for author in book.authors:
            if author.name not in update_authors:
                book.authors.remove(author)
        # added
        for author_name in update_authors:
            if author_name not in [a.name for a in book.authors]:
                book.authors.append(Author(author_name))

        # thumbnail
        if update_thumbnail_url and book.thumbnail_url != update_thumbnail_url:
            book.thumbnail_url = update_thumbnail_url
            title = [c for c in book.title.replace(' ', '_')
                     if re.match(r'\w', c)]
            image_name = ''.join(title) + book.isbn13 + '.jpg'

            img = open(THUMBNAILS_ABSOLUTE_DIR + image_name, 'wb')
            img.write(urllib_request.urlopen(book.thumbnail_url).read())
            book.image_name = image_name

        # preview url
        if update_preview_url and book.preview_url != update_preview_url:
            book.preview_url = update_preview_url

        session.commit()

        flash("The book has been updated successfully!")
    except RuntimeError as rte:
        flash("Something has gone wrong! <br>%s" % str(rte), 'error')

    return redirect('books/edit')


@mod.route('/view', methods=['GET'])
def view_books(ready_books=None):
    """Display books in the library.

    Defaults to displaying available books only.
    If `include_unavailable` parameter is set in the `request`,
    it display all books; this is used in the admin view.
    """
    session = db_session()

    # get search cache
    search_cache = []

    for book_title in session.query(Book.title).distinct():
        search_cache.append(book_title[0])

    for category_name in session.query(Category.name).distinct():
        search_cache.append(category_name[0])

    for author_name in session.query(Author.name).distinct():
        search_cache.append(author_name[0])

    search_cache.sort()

    # initialise loan forms
    new_loan_form, loan_return_form = init_loan_forms()

schoollibrary/bpslibrary/views/loans.py
"""
Loans
=====

A view to handle loans and returns of books."""

from datetime import datetime
from flask import Blueprint, flash, render_template, request
from flask_login import login_required, current_user
from flask_paginate import Pagination, get_page_parameter
from sqlalchemy import and_
from werkzeug.utils import secure_filename
from bpslibrary import app
from bpslibrary.database import db_session
from bpslibrary.models import Book, Classroom, Pupil, User, Loan
from bpslibrary.utils.nav import redirect_to_previous
from bpslibrary.utils.barcode import scan_for_isbn
from bpslibrary.forms import NewLoanForm, LoanReturnForm
from bpslibrary.utils.enums import BookLocation


mod = Blueprint('loans', __name__, url_prefix='/loans')
THUMBNAILS_DIR = app.config['THUMBNAILS_DIR']
PER_PAGE = app.config['PER_PAGE']


@mod.route('/record', methods=['POST'])
@login_required
def record_loan():
    """Records loan of a book to a pupil."""
    session = db_session()
    new_loan_form = NewLoanForm()

    class_id = current_user.classroom.id
    new_loan_form.pupil_id.choices = \
        [(p[0], p[1]) for p in session.query(Pupil.id, Pupil.name).
         filter(Pupil.classroom_id == class_id)]
    try:
        user = User.query.filter(
            User.id == int(new_loan_form.user_id.data)
            ).first()
        pupil = Pupil.query.filter(
            Pupil.id == int(new_loan_form.pupil_id.data)
            ).first()
        book = Book.query.filter(
            Book.id == int(new_loan_form.book_id.data)
            ).first()

        if not user or not pupil or not book:
            raise ValueError(
                "Invalid entries! Book: %s; Pupil: %s; User: %s" %
                (str(book), str(pupil), str(user))
            )

        if not new_loan_form.barcode_img.data:
            raise ValueError(
                "No barcode image provided. Please scan the barcode."
            )

        isbnlist = scan_for_isbn(request.files[new_loan_form.barcode_img.name])

        if len(isbnlist) < 1:
            raise ValueError(
                "No ISBN found in provided image."
            )

        if book.isbn13 not in isbnlist:
            raise ValueError(
                "Barcode does not match selected book."
            )

        loan = Loan()
        loan.pupil = pupil
        loan.book = book
        loan.start_date = datetime.date(datetime.now())

        book.current_location = BookLocation.LOAN.value

        session.add(loan)
        session.commit()
        flash("Loan has been recorded for '%s' to %s" %
              (book.title, pupil.name))

    except ValueError as val_err:
        flash(str(val_err), 'error')

    return redirect_to_previous(True)


@mod.route('/return', methods=['POST'])
@login_required
def record_return():
    """Records return of a book."""
    session = db_session()
    loan_return_form = LoanReturnForm()

    try:
        book = Book.query.filter(
            Book.id == int(loan_return_form.book_id.data)
            ).first()

        if not book:
            raise ValueError("Invalid entries!")

        if not loan_return_form.barcode_img.data:
            raise ValueError(
                "No barcode image provided. Please scan the barcode.")

        isbnlist = scan_for_isbn(
            request.files[loan_return_form.barcode_img.name])

        if len(isbnlist) < 1:
            raise ValueError("No ISBN found in provided image.")

        if book.isbn13 not in isbnlist:
            raise ValueError("Barcode does not match selected book.")

        loan = book.current_loan

        if not loan:
            raise ValueError("No loans found for this book.")

        loan.end_date = datetime.date(datetime.now())
        book.current_location = BookLocation.LIBRARY.value

        session.commit()
        flash("Book return has been recorded for '%s' by %s" %
              (book.title, loan.pupil.name))

    except ValueError as val_err:
        flash(str(val_err), 'error')
    return redirect_to_previous(True)


@mod.route('/view', methods=['GET'])
@login_required
def view_loans():
    """Displays loans of a book, or of all books."""
    session = db_session()
    if current_user.is_admin:
        found_books = session.query(Book).filter(
            Book.current_location == BookLocation.LOAN.value).all()
    else:
        found_books = session.query(Book).filter(
            Book.current_location == BookLocation.LOAN.value and
            Book.id in [l.book_id for l in Classroom.query(
                Classroom.user_id == current_user.id).open_loans]).all()

    # pagination
    total = len(found_books)
    page = request.args.get(get_page_parameter(), type=int, default=1)
    pagination = Pagination(page=page,
                            total=total,
                            per_page=PER_PAGE,
                            css_framework="bootstrap3")

    # initialise loan forms
    new_loan_form, loan_return_form = init_loan_forms()

    return render_template('loans.html',
                           books=found_books,
                           new_loan_form=new_loan_form,
                           loan_return_form=loan_return_form,
                           pagination=pagination,
                           thumbnails_dir=THUMBNAILS_DIR)


def init_loan_forms():
    """Initialise a new_loan and loan_return forms."""
    session = db_session()

    new_loan_form = None
    loan_return_form = None

    if current_user.is_authenticated:
        loan_return_form = LoanReturnForm()
        if current_user.classroom:
            new_loan_form = NewLoanForm()
            class_id = current_user.classroom.id
            new_loan_form.pupil_id.choices = \
                [(p[0], p[1]) for p in session.query(Pupil.id, Pupil.name).
                 filter(Pupil.classroom_id == class_id)]

    return new_loan_form, loan_return_form

schoollibrary/bpslibrary/templates/access.html
<!-- Access -->

{% extends "base.html" %}
{% block title %}Access - {{ super() }}{% endblock %}

{% block header %}
    {% if login_form %}
        Login
    {% elif new_access_form %}
        Setup Access
    {% else %}
        User Access Management
    {% endif %}
{% endblock %}
{% block content %}

{% if login_form %}  
    <form method="POST" >
        {{ login_form.csrf_token }}
        <div class="form-group col-md-4">
            {{ login_form.username.label }}
            {{ login_form.username(class_="form-control") }}
            <small class="help-block text-muted-green">
                {{ login_form.username.description }}
            </small>
        </div>
        <div class="form-group col-md-4">
            {{ login_form.password.label }}
            {{ login_form.password(class_="form-control") }}
        </div>
        <div class="col-md-12"> 
            <input class="btn btn-primary bps-btn" type="submit" value="Log in">
        </div>
    </form>
{% elif new_access_form %} 
    <form method="POST">
        {{ new_access_form.csrf_token }}
        <div class="form-group col-md-3">
            {{ new_access_form.classroom.label }}
            {{ new_access_form.classroom(class_="form-control") }}
        </div>
        <div class="form-group col-md-4">
            {{ new_access_form.username.label }}
            {{ new_access_form.username(class_="form-control") }}
        </div>
        <div class="form-group col-md-4">
            {{ new_access_form.password.label }} 
            {{ new_access_form.password(class_="form-control") }}
        </div>
        <div class="form-group col-md-1">
            {{ new_access_form.is_admin.label }} 
            {{ new_access_form.is_admin(class_="form-control") }}
        </div>
        <div class="col-md-12"> 
            <input class="btn btn-primary bps-btn" type="submit" value="Create Access">
        </div>
    </form>
{% endif %}

{% endblock %}

schoollibrary/bpslibrary/templates/add_book.html
{% extends "base.html" %}

{% block title %}Add books - {{ super() }}{% endblock %}
{% block header %}Add Books{% endblock %}
{% block content %}
<div class="container-fluid">
    <div id="add-book" class="panel-group">
        <div class="panel panel-info">
            <div class="panel-heading">
                <h3 class="panel-title text-info">
                    <div class="container-fluid">
                        <a data-toggle="collapse" data-parent="#add-book" href="#lookup-panel">
                            Lookup a book
                        </a>
                    </div>
                </h3>
            </div>
            <div id="lookup-panel" class="panel-collapse collapse in">
                <div class="panel-body">
                    <form name="lookup_book" 
                          method="POST" 
                          action="{{ url_for('books.lookup_book') }}" 
                          enctype="multipart/form-data">
                        <h3 class="text-info">Lookup a book</h3>
                        <br>
                        <div class="form-group">
                            <label><span class="glyphicon glyphicon-barcode"></span> Barcode</label>
                            <br>
                            <label id="barcode_btn" class="btn btn-default" for="barcode">Scan Barcode</label>
                            <br>
                            <input class="hidden" type="file" id="barcode" name="barcode" 
                                   accept="image/*" capture="camera">
                            <small class="text-muted-green">
                                Take a picture of the barcode using tablet/phone camera or upload and image of the barcode.
                            </small> 
                        </div>
                        <div class="form-group">
                            <label class="text-default" for="lkp-isbn">ISBN
                            </label>
                            <input class="form-control" type="text" id="lkp-isbn" name="isbn" 
                                    placeholder="Enter the ISBN e.g. 9781509804757" value="{{ search_isbn }}">
                            <small class="text-muted-green">
                                Either the 10 or 13 digits long ISBN without hyphens (-) or spaces
                            </small> 
                        </div>
                        <div class="form-group">
                            <label for="lkp-book-title">Title</label>
                            <input id="lkp-book-title" class="form-control" type="text" name="book_title" 
                                    placeholder="Enter book title" value="{{ search_title }}">
                            <small class="text-muted-green">Not needed if the ISBN is provided</small>
                        </div>
                        <button class="bps-btn btn btn-primary" type="submit">Lookup book details</button>
                    </form>
                </div>
            </div>
        </div>
        <!-- Manual add book -->
        <div class="panel panel-info">
            <div class="panel-heading">
                <h3 class="panel-title text-info">
                    <div class="container-fluid">
                        <a data-toggle="collapse" data-parent="#add-book" href="#manual-add-panel">
                            <span class="text-info">Enter book detials</span>
                        </a>
                    </div>
                </h3>
            </div>
            <div id="manual-add-panel" class="panel-collapse collapse">
                <div class="panel-body">
                    <form name="manual_add_book" method="POST" action="{{ url_for('books.add_book') }}" >
                        <h3 class="text-info">Enter book detials</h3>
                        <br>
                        <div class="form-group">
                            <label for="ma-isbn13">ISBN 13</label>
                            <input class="form-control" type="text" id="ma-isbn13" name="isbn13" 
                                    aria-describedby="ma-isbn13-help"
                                    placeholder="Enter the 13 digit ISBN e.g. 9781509804757">
                            <small id="ma-isbn13-help" class="help-block text-muted-green">
                                Enter the 13 digit long ISBN without hyphens (-) or spaces
                            </small>
                        </div>
                        <div class="form-group">
                            <label for="ma-isbn10">ISBN 10</label>
                            <input class="form-control" type="text" id="ma-isbn10" name="isbn10" 
                                    aria-describedby="ma-isbn10-help" 
                                    placeholder="Enter the 10 digit ISBN e.g. 1509804757">
                            <small id="ma-isbn10-help" class="help-block text-muted-green">
                                Enter the 10 digit long ISBN without hyphens (-) or spaces
                            </small> 
                        </div>
                        <div class="form-group">
                            <label for="ma-book-title">Title</label>
                            <input id="ma-book-title" class="form-control" type="text" name="book_title" 
                                    placeholder="Enter book title"> 
                        </div>
                        <div class="form-group">
                            <label for="ma-description">Description</label>
                            <textarea id="ma-description" class="form-control" rows="5" name="book_description" 
                                    aria-describedby="ma-description-help"></textarea>
                            <small id="ma-description-help" class="help-block text-muted-green">
                                This is the blurb usually on the back of the book
                            </small>
                        </div>
                        <div class="form-group">
                            <label for="ma-author">Author</label>
                            <input id="ma-author" class="form-control" type="text" name="book_author" 
                                    placeholder="Enter name of the author(s)">
                            <small class="form-text text-muted-green">
                                Separate multiple authors with a comma e.g. Jane Bloggs, John Smith
                            </small> 
                        </div>
                        <div class="form-group">
                            <label for="ma-category">Category</label>
                            <input id="ma-category" class="form-control" type="text" name="book_category" 
                                    placeholder="Enter category"> 
                            <small class="form-text text-muted-green">
                                Separate multiple categories with a comma e.g. Nonfiction, Animals
                            </small> 
                        </div>
                        <button class="bps-btn btn btn-primary" type="submit">Add book</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

<!-- Found books -->

    <div class="panel-group" id="found_books">
        {% for book in found_books %}
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    <div class="container-fluid">
                        <a data-toggle="collapse" data-parent="#found_books" href="#found-book-{{ loop.index }}" >
                            <div class="row">
                                <div class="col-sm-2">
                                    <img class="img-responsive img-thumbnail" src="{{ book.thumbnail_url }}">
                                </div>
                                <div>
                                    <br>
                                    <span class="glyphicon glyphicon-expand pull-left"> </span>
                                </div>
                                <div class="col-sm-9">
                                    <div>{{ book.title }}</div>
                                    <div><h5 class="text-muted-green">{{ book.short_description | safe }}</h5></div>
                                </div>
                            </div>
                        </a>
                    </div>
                </h4>
                <div>
                    <a class="col-xs-offset-2" href="{{ book.preview_url }}" target="blank">Preview online >></a>
                </div>
            </div>        
            <div id="found-book-{{ loop.index }}" class="panel-collapse collapse out">
                <div class="panel-body">
                    <form method="POST" action="{{ url_for('books.add_book') }}">
                        <input name="preview_url" class="hidden" value="{{ book.preview_url }}">
                        <input name="thumbnail_url" class="hidden" value="{{ book.thumbnail_url }}">
                        <div class="form-group">
                            <label for="ma-isbn13">ISBN 13</label>
                            <input class="form-control" type="text" id="ma-isbn13" name="isbn13" 
                                    aria-describedby="ma-isbn13-help"
                                    placeholder="Enter the 13 digit ISBN e.g. 9781509804757"
                                    value="{{ book.isbn13 }}">
                            <small id="ma-isbn13-help" class="help-block text-muted-green">
                                The 13 digit long ISBN without hyphens (-) or spaces
                            </small>
                        </div>
                        <div class="form-group">
                            <label for="ma-isbn10">ISBN 10</label>
                            <input class="form-control" type="text" id="ma-isbn10" name="isbn10" 
                                    aria-describedby="ma-isbn10-help" 
                                    placeholder="Enter the 10 digit ISBN e.g. 1509804757"
                                    value="{{ book.isbn10 }}">
                            <small id="ma-isbn10-help" class="help-block text-muted-green">
                                The 10 digit long ISBN without hyphens (-) or spaces
                            </small> 
                        </div>
                        <div class="form-group">
                            <label for="ma-book-title">Title</label>
                            <input id="ma-book-title" class="form-control" type="text" name="book_title" 
                                    placeholder="Enter book title"
                                    value="{{ book.title }}"> 
                        </div>
                        <div class="form-group">
                            <label for="ma-description">Description</label>
                            <textarea id="ma-description" class="form-control" rows="5" name="book_description" 
                                    aria-describedby="ma-description-help">{{ book.description | safe }}</textarea>
                            <small id="ma-description-help" class="help-block text-muted-green">
                                This is the blurb usually on the back of the book
                            </small>
                        </div>
                        <div class="form-group">
                            <label for="ma-author">Author</label>
                            <input id="ma-author" class="form-control" type="text" name="book_authors" 
                                    placeholder="Enter name of the author(s)"
                                    value="{{ book.authors_names }}">
                            <small class="form-text text-muted-green">
                                Separate multiple authors with a comma e.g. Jane Bloggs, John Smith
                            </small> 
                        </div>
                        <div class="form-group">
                            <label for="ma-category">Category</label>
                            <input id="ma-category" class="form-control" type="text" name="book_categories" 
                                    placeholder="Enter category"
                                    value="{{ book.categories_names }}"> 
                            <small class="form-text text-muted-green">
                                Separate multiple categories with a comma e.g. Nonfiction, Animals
                            </small> 
                        </div>
                        <button class="bps-btn btn btn-primary" type="submit">Add book</button>
                    </form>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>

</div>

{% endblock content %}

{% block scripts %}
    {{ super() }}
    <script type="text/javascript">
        $(document).ready(
            function(){
                $('.collapse')
                    .on('show.bs.collapse', 
                        function(){
                            $(this).parent().find(".glyphicon-expand")
                                .removeClass("glyphicon-expand")
                                .addClass("glyphicon-collapse-down");
                    })
                    .on('hide.bs.collapse', 
                        function(){
                            $(this).parent().find(".glyphicon-collapse-down")
                                .removeClass("glyphicon-collapse-down")
                                .addClass("glyphicon-expand");
                    });
            });
    </script>
{% endblock %}